# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:12000"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: # create the volume for persisting data.
